spring:
  application:
    name: eureka-client-2
  profiles:
    active: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8090