management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build.enabled: true
    git.enabled: true
    os.enabled: true
    java.enabled: true
    env.enabled: true
info:
  app:
    encoding: "UTF-8"
    java:
      source: "17"
      target: "17"
